name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${VERSION}"

      - name: Trigger Homebrew formula update
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.HOMEBREW_TAP_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/manudiv16/homebrew-eaws/dispatches \
            -d "{\"event_type\":\"new-release\",\"client_payload\":{\"version\":\"${{ steps.version.outputs.VERSION }}\"}}"
          
          echo "✅ Homebrew formula update triggered for version ${{ steps.version.outputs.VERSION }}"

      - name: Wait for formula update
        run: |
          echo "🕐 Waiting for formula update to complete..."
          sleep 30
          
          # Check if the formula was updated
          FORMULA_VERSION=$(curl -s https://raw.githubusercontent.com/manudiv16/homebrew-eaws/main/Formula/eaws.rb | grep 'version' | head -1 | sed 's/.*"\(.*\)".*/\1/')
          echo "Current formula version: ${FORMULA_VERSION}"
          
          if [ "${FORMULA_VERSION}" == "${{ steps.version.outputs.VERSION }}" ]; then
            echo "✅ Formula successfully updated to version ${{ steps.version.outputs.VERSION }}"
          else
            echo "⚠️  Formula version (${FORMULA_VERSION}) doesn't match release version (${{ steps.version.outputs.VERSION }})"
            echo "This might be expected if the update is still in progress."
          fi
